DROP TABLE Equipment;
CREATE TABLE Equipment(
   CardID      INTEGER  NOT NULL 
  ,EquipmentID INTEGER  NOT NULL
  ,Slot        VARCHAR(18) NOT NULL
  ,Brand       VARCHAR(18) NOT NULL
constraint equipment_pk1 primary key (EquipmentID,CardID),
constraint equipment_fk1 foreign key (CardID) references Cards(CardID)
);
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (76481,1,'Cleats','Adidas');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (56379,2,'Batting Gloves','Adidas');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (41559,3,'Fielding Glove','Adidas');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (52504,4,'Cleats','Adidas');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (99322,5,'Cleats','Adidas');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (87460,6,'Fielding Glove','All-Star');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (69015,7,'Catcher Masks','All-Star');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (47403,8,'Chest Protector','All-Star');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (48195,9,'Leg Guards','All-Star');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (59564,10,'Bat','Axe Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (17515,11,'Bat','Axe Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (34790,12,'Bat','Axe Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (60791,13,'Bat','Axe Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (54138,14,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (56067,15,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (99045,16,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (24222,17,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (50301,18,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (28182,19,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (50563,20,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (30870,21,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (41008,22,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (76270,23,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (31237,24,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (41426,25,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (57502,26,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (37291,27,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (85103,28,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (63685,29,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (78403,30,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (97404,31,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (95856,32,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (25301,33,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (75335,34,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (42574,35,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (58804,36,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (20624,37,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (20095,38,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (92474,39,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (47790,40,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (92623,41,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (73366,42,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (74307,43,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (39424,44,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (90262,45,'Bat','Bat Skin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (50310,46,'Batting Gloves','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (29537,47,'Catcher Masks','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (68460,48,'Elbow Guard','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (23320,49,'Batting Gloves','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (34911,50,'Chest Protector','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (58504,51,'Shin Guard','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (91681,52,'Leg Guards','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (64138,53,'Compression Sleeve','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (98449,54,'Wrist Guard','EvoShield');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (80324,55,'Batting Gloves','Franklin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (40391,56,'Shin Guard','Franklin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (18637,57,'Wrist Guard','Franklin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (50349,58,'Batting Gloves','Franklin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (76740,59,'Elbow Guard','Franklin');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (33351,60,'Cleats','Jordan');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (81818,61,'Batting Gloves','Jordan');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (48249,62,'Cleats','Jordan');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (25875,63,'Cleats','Jordan');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (12323,64,'Bat Grips','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (31314,65,'Bat Grips','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (74599,66,'Batting Gloves','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (41745,67,'Ritual','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (39679,68,'Bat Grips','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (90383,69,'Bat Grips','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (86452,70,'Batting Gloves','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (79516,71,'Ritual','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (50770,72,'Batting Gloves','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (74100,73,'Bat Grips','Lizard Skins');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (52773,74,'Bat','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (87820,75,'Fielding Glove','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (72001,76,'Fielding Glove','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (14471,77,'Bat','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (90465,78,'Batting Gloves','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (97123,79,'Bat','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (52995,80,'Fielding Glove','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (79145,81,'Bat','Louisville Slugger');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (28549,82,'Fielding Glove','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (69805,83,'Bat','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (69575,84,'Batting Gloves','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (37103,85,'Batting Gloves','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (71412,86,'Fielding Glove','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (82249,87,'Bat','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (98127,88,'Batting Gloves','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (15164,89,'Bat','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (84632,90,'Bat','Marucci');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (28470,91,'Cleats','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (90522,92,'Batting Gloves','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (82382,93,'Fielding Glove','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (93311,94,'Bat','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (29865,95,'Cleats','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (67846,96,'Fielding Glove','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (48757,97,'Batting Gloves','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (79601,98,'Bat','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (91033,99,'Cleats','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (89215,100,'Fielding Glove','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (20351,101,'Batting Gloves','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (12296,102,'Bat','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (11917,103,'Bat','Mizuno');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (81673,104,'Cleats','New Balance');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (37718,105,'Cleats','New Balance');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (66977,106,'Cleats','New Balance');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (11425,107,'Batting Gloves','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (33747,108,'Fielding Glove','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (40322,109,'Cleats','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (14408,110,'Eyewear','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (61085,111,'Wrist Guard','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (45443,112,'Cleats','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (91837,113,'Eyewear','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (33477,114,'Batting Gloves','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (73897,115,'Cleats','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (14167,116,'Fielding Glove','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (46590,117,'Compression Sleeve','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (59599,118,'Fielding Glove','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (91472,119,'Batting Gloves','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (75654,120,'Cleats','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (16131,121,'Elbow Guard','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (74761,122,'Shin Guard','Nike');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (71674,123,'Bat','Old Hickory');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (53773,124,'Batting Gloves','Old Hickory');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (31390,125,'Bat','Old Hickory');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (47783,126,'Bat','Old Hickory');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (37829,127,'Bat','Old Hickory');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (96005,128,'Bat','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (45718,129,'Batting Gloves','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (64031,130,'Fielding Glove','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (54449,131,'Catcher Masks','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (75866,132,'Batting Gloves','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (93857,133,'Bat','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (93432,134,'Fielding Glove','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (40932,135,'Chest Protector','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (26068,136,'Bat','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (12191,137,'Batting Gloves','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (80009,138,'Fielding Glove','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (74312,139,'Bat','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (91227,140,'Leg Guards','Rawlings');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (60294,141,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (62109,142,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (40161,143,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (35389,144,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (79915,145,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (13059,146,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (67248,147,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (69340,148,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (25806,149,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (63227,150,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (55781,151,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (88933,152,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (63836,153,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (53711,154,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (59466,155,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (61538,156,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (13381,157,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (22158,158,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (82298,159,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (37533,160,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (72721,161,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (75734,162,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (11333,163,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (45960,164,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (64346,165,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (93531,166,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (47113,167,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (77296,168,'Ritual','Ritual');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (46469,169,'Bat','Sam Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (83966,170,'Bat','Sam Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (74328,171,'Batting Gloves','Sam Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (43574,172,'Bat','Sam Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (69545,173,'Bat','Sam Bat');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (65671,174,'Bat','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (75510,175,'Fielding Glove','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (26814,176,'Bat','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (52894,177,'Fielding Glove','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (54358,178,'Bat','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (36190,179,'Bat','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (43683,180,'Fielding Glove','SSK');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (15345,181,'Socks','STANCE');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (36699,182,'Socks','STANCE');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (29062,183,'Socks','STANCE');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (33296,184,'Bat','Trinity Bat Co');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (49875,185,'Batting Gloves','Trinity Bat Co');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (60767,186,'Bat','Trinity Bat Co');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (50912,187,'Bat','Trinity Bat Co');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (75423,188,'Bat','Trinity Bat Co');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (55333,189,'Batting Gloves','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (82869,190,'Cleats','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (20354,191,'Catcher Masks','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (98128,192,'Fielding Glove','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (40383,193,'Compression Sleeve','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (63680,194,'Eyewear','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (33601,195,'Batting Gloves','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (67096,196,'Fielding Glove','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (49012,197,'Cleats','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (36676,198,'Chest Protector','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (83503,199,'Elbow Guard','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (60090,200,'Eyewear','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (35960,201,'Leg Guards','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (27995,202,'Shin Guard','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (45522,203,'Wrist Guard','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (83983,204,'Eyewear','Under Armour');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (47880,205,'Ritual','Varo');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (65855,206,'Ritual','Varo');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (88351,207,'Ritual','Varo');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (67951,208,'Bat','Victus');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (19272,209,'Bat','Victus');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (95846,210,'Batting Gloves','Victus');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (55792,211,'Bat','Victus');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (77517,212,'Bat','Victus');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (69886,213,'Fielding Glove','Wilson');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (20736,214,'Fielding Glove','Wilson');
INSERT INTO Equipment(CardID,EquipmentID,Slot,Brand) VALUES (81784,215,'Fielding Glove','Wilson');