DROP TABLE Unlockables;
CREATE TABLE Unlockables(
   CardID       INTEGER  NOT NULL 
  ,UnlockableID INTEGER  NOT NULL
  ,UnlockableCategory VARCHAR(40) NOT NULL
  ,UnlockableSubcategory VARCHAR(9) NOT NULL,
constraint unlock_pk1 primary key (UnlockableID,CardID),
constraint unlock_fk1 foreign key (CardID) references Cards(CardID)
);
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (84908,1,'Spring','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (64809,2,'The Spear LH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (28462,3,'The Spear RH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (57611,4,'The Spear LH2','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (15141,5,'The Spear RH2','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (87081,6,'Cartoon Stumble Run','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (27633,7,'Sombrero Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (54497,8,'Clumsy Ice Cream Cone Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (78227,9,'Under The Lights Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (56802,10,'Space Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (49041,11,'Skateboarding Icon','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (18599,12,'Bigfoot Is Real? Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (13883,13,'See. You. Later!','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (47532,14,'DJ Air Horn','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (43974,15,'Bruh','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (52199,16,'Glass Shattering','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (46359,17,'Tires Squeaking','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (83009,18,'Touchdown','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (61988,19,'Siren','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (96078,20,'Vuvuzela','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (96137,21,'World Series Trophy Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (48322,22,'It''s Outta Here!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (84957,23,'Gorilla Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (57472,24,'Rooster Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (14899,25,'Lizard Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (20047,26,'Purple Dog Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (87720,27,'Guitar Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (42517,28,'Purple Dog Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (29633,29,'Lonely Carrot Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (58587,30,'Grass Is Always... Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (96417,31,'Dusty Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (81353,32,'Lotta Leaves Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (29176,33,'Mouse Trap Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (35503,34,'Feather Weather Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (32444,35,'Octopus Arms Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (55018,36,'Foul Pole Nameplate','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (55435,37,'The Reverse Flip LH2','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (81294,38,'The Lean Back LH2','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (94116,39,'Good Bye, Home Run!','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (33217,40,'Ole','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (54340,41,'Airplane','Nameplate');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (73576,42,'Octopus Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (15347,43,'Elephant Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (55304,44,'Bunny Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (61148,45,'Bull Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (57877,46,'Cat Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (22553,47,'Cowboy Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (45135,48,'Pirate Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (40626,49,'Jet Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (37925,50,'Orange Camo Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (39945,51,'What Was That? Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (89724,52,'Omakase Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (81107,53,'Happy Place Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (77486,54,'Cold Zone Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (66054,55,'Do Ghosts Have Hands? Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (79336,56,'The Lot Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (82334,57,'It''s Got a Chance... Gone!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (22644,58,'With Emphasis LH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (31499,59,'It Is Outta Here!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (77955,60,'There It Goes... See Ya!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (98087,61,'It''s Grand Salami Time!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (74260,62,'Swung On And Belted!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (26516,63,'It Might Be... It Could Be... It''s Gone!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (19767,64,'And, That Baby''s Gone!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (90487,65,'Clown Car','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (41072,66,'Cartoon Whoosh','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (59336,67,'Crowd Laugh','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (21686,68,'Cartoon Run ''N'' Scoot','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (14564,69,'Dinosaur Roar','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (34001,70,'Lick','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (81805,71,'Whip Crack','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (24885,72,'Explosion','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (19064,73,'Pixelated Baseball Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (55504,74,'Home Run Derby® Trophy Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (78665,75,'Gold Glove Trophy Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (78767,76,'MVP Award Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (16730,77,'Pixelated Player Jumping Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (70662,78,'Pixelated Batter 01 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (31154,79,'Pixelated Batter 02 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (80318,80,'Pixelated Pitcher 01 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (76362,81,'Pixelated Pitcher 02 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (17124,82,'Pixelated Player Running 01 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (44800,83,'Pixelated Player Running 02 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (61313,84,'Eye Black Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (40709,85,'Chalk Lines Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (36136,86,'Booyea!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (16597,87,'Everyone Watches It Fly!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (98820,88,'Back, Back, Back, Gone!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (96982,89,'Break Out the Tape Measure!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (76500,90,'Studio Pet 10 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (73641,91,'Watch It Fly! LH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (87878,92,'And That One Is Gone!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (54594,93,'I Don''t Believe It!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (60165,94,'Guitar Smash','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (50313,95,'Cleat Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (86106,96,'Studio Pet 03 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (38631,97,'Studio Pet 04 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (23763,98,'Studio Pet 05 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (43523,99,'Studio Pet 06 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (52760,100,'Fastball Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (43795,101,'Bunting Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (18792,102,'Bubble Gum Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (70000,103,'Diving Catch Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (21077,104,'Broken Bat Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (99994,105,'Sunflower Seeds Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (85062,106,'Home Plate Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (11573,107,'Hot Dog Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (83364,108,'Grass Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (54074,109,'Shocked Baseball Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (62579,110,'Telekinesis','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (95049,111,'The Fade Away','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (83939,112,'Tug of War','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (44572,113,'Watch It Fly! LH2','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (34388,114,'The Fisherman LH2','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (59339,115,'Strut Your Stuff RH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (49260,116,'The Fisherman RH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (49029,117,'Nonchalant RH2','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (76119,118,'Adios Pelota!','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (28661,119,'Studio Pet 07 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (73964,120,'Studio Pet 08 Icon','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (61268,121,'Peanuts Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (72503,122,'Stitching Nameplate','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (45676,123,'Out of Breath','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (54827,124,'Bean Bag Race','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (67596,125,'The Caddie','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (32198,126,'Smooth as Silk LH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (61868,127,'Natural Flip LH2','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (78299,128,'Watch It Fly! RH1','Icon');
INSERT INTO Unlockables(CardID,UnlockableID,UnlockableCategory,UnlockableSubcategory) VALUES (64318,129,'Watch It Fly! RH2','Icon');
